#!/usr/bin/env python3

tpl = '''# THIS FILE IS AUTOGENERATED -- DO NOT EDIT #
#   Edit and Re-run .ci/gitlab/template.ci.py instead       #

stages:
  - test

.test_base:
    retry:
        max: 2
        when:
            - runner_system_failure
            - stuck_or_timeout_failure
            - api_failure
    only: ['branches', 'tags', 'triggers', 'merge-requests']
    except:
        - /^staging/.*$/i

pages:
    extends: .test_base
    image: pymor/testing:3.7
    stage: test
    cache:
      paths:
        - public
    script: .ci/gitlab/test_docs.bash
    # only:
    #   - master
    #   - tags
    artifacts:
        paths:
            - public

# THIS FILE IS AUTOGENERATED -- DO NOT EDIT #
#   Edit and Re-run .ci/gitlab/template.ci.py instead       #

'''


import os
import jinja2
import sys
from itertools import product
tpl = jinja2.Template(tpl)
pythons = ['3.6', '3.7']
# these should be all instances in the federation
binder_urls = ['https://gke.mybinder.org/build/gh/pymor/pymor',
               'https://ovh.mybinder.org/build/gh/pymor/pymor']
marker = ["Vanilla", "PIP_ONLY", "NOTEBOOKS"]
with open(os.path.join(os.path.dirname(__file__), 'ci.yml'), 'wt') as yml:
    matrix = list(product(pythons, marker))
    yml.write(tpl.render(matrix=matrix,testos=['debian_buster', 'debian_testing', 'centos_7'], pythons=pythons,
                         binder_urls=binder_urls))
